language: python
cache: pip
sudo: false
cache: pip
python:
  - 2.6
  - 2.7
  - 3.4
install:
  - pip install -r requirements.txt
  - pip install coveralls
script: python setup.py nosetests --with-coverage --cover-package=pssh
notifications:
  email:
    on_failure: change
after_success:
  - coveralls
sudo: false
